##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(ALBONJOURDISCOVERY)
set(ALBONJOURDISCOVERY_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/albonjourdiscovery/;${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(ALBONJOURDISCOVERY_DEFINITIONS  "HAVE_IPV6" CACHE STRING "" FORCE)
set(ALBONJOURDISCOVERY_DEPENDS      "PROXIES;LIBTHREAD;LIBCORE;BOOST;PTHREAD;BOOST_SIGNALS;TOOLS;BOOST_FILESYSTEM;ALVALUE"     CACHE STRING "" FORCE)

#cleanup this temp var
set(ALBONJOURDISCOVERY_tempdebug "ALBONJOURDISCOVERY_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(ALBONJOURDISCOVERY_tempdebug albonjourdiscovery_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (ALBONJOURDISCOVERY_tempdebug)
  #use debug and optimized version
  flib(ALBONJOURDISCOVERY OPTIMIZED albonjourdiscovery   PATHS "${_ROOT_DIR}/../../")
  flib(ALBONJOURDISCOVERY DEBUG     albonjourdiscovery_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(ALBONJOURDISCOVERY albonjourdiscovery PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(ALBONJOURDISCOVERY)
