##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(ALCOMMON)
set(ALCOMMON_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/alcommon/;${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(ALCOMMON_DEFINITIONS  "TIXML_USE_STL;TIXML_USE_STL" CACHE STRING "" FORCE)
set(ALCOMMON_DEPENDS      "LIBIPPC;BOOST_SERIALIZATION;BOOST_DATE_TIME;BOOST_THREAD;ALVALUE;LIBCORE;BOOST;PTHREAD;BOOST_SIGNALS;TOOLS;BOOST_FILESYSTEM;LIBFINDIPPC;DL;PROXIES;LIBSOAP;TINYXML;RTTOOLS;LIBTHREAD;BOOST_PROGRAM_OPTIONS;LIBFACTORY;PYTHON-STATIC"     CACHE STRING "" FORCE)

#cleanup this temp var
set(ALCOMMON_tempdebug "ALCOMMON_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(ALCOMMON_tempdebug alcommon_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (ALCOMMON_tempdebug)
  #use debug and optimized version
  flib(ALCOMMON OPTIMIZED alcommon   PATHS "${_ROOT_DIR}/../../")
  flib(ALCOMMON DEBUG     alcommon_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(ALCOMMON alcommon PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(ALCOMMON)
