##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(ALMATH)
set(ALMATH_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/almath/;${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(ALMATH_DEFINITIONS  "" CACHE STRING "" FORCE)
set(ALMATH_DEPENDS      ""     CACHE STRING "" FORCE)

#cleanup this temp var
set(ALMATH_tempdebug "ALMATH_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(ALMATH_tempdebug almath_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (ALMATH_tempdebug)
  #use debug and optimized version
  flib(ALMATH OPTIMIZED almath   PATHS "${_ROOT_DIR}/../../")
  flib(ALMATH DEBUG     almath_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(ALMATH almath PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(ALMATH)
