##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(ALSTREAMER)
set(ALSTREAMER_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(ALSTREAMER_DEFINITIONS  "" CACHE STRING "" FORCE)
set(ALSTREAMER_DEPENDS      "BOOST;GSTREAMER;XML2;GLIB;BOOST_FILESYSTEM"     CACHE STRING "" FORCE)

#cleanup this temp var
set(ALSTREAMER_tempdebug "ALSTREAMER_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(ALSTREAMER_tempdebug alstreamer_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (ALSTREAMER_tempdebug)
  #use debug and optimized version
  flib(ALSTREAMER OPTIMIZED alstreamer   PATHS "${_ROOT_DIR}/../../")
  flib(ALSTREAMER DEBUG     alstreamer_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(ALSTREAMER alstreamer PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(ALSTREAMER)
