##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(ALVALUE)
set(ALVALUE_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/alvalue/;${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(ALVALUE_DEFINITIONS  "" CACHE STRING "" FORCE)
set(ALVALUE_DEPENDS      "LIBCORE;BOOST;PTHREAD;BOOST_SIGNALS;TOOLS;BOOST_FILESYSTEM"     CACHE STRING "" FORCE)

#cleanup this temp var
set(ALVALUE_tempdebug "ALVALUE_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(ALVALUE_tempdebug alvalue_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (ALVALUE_tempdebug)
  #use debug and optimized version
  flib(ALVALUE OPTIMIZED alvalue   PATHS "${_ROOT_DIR}/../../")
  flib(ALVALUE DEBUG     alvalue_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(ALVALUE alvalue PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(ALVALUE)
