##
## findmodule.cmake
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(CHOREGRAPHE)
fprogram(CHOREGRAPHE_binary choregraphe-bin)
set(CHOREGRAPHE_EXECUTABLE ${CHOREGRAPHE_binary} CACHE STRING "" FORCE)
export_bin(CHOREGRAPHE)
