##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(CHOREGRAPHE-PLUGINS)
set(CHOREGRAPHE-PLUGINS_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(CHOREGRAPHE-PLUGINS_DEFINITIONS  "TIXML_USE_STL" CACHE STRING "" FORCE)
set(CHOREGRAPHE-PLUGINS_DEPENDS      "QT_QTCORE;QT_QTGUI;LIBCORE;BOOST;PTHREAD;BOOST_SIGNALS;TINYXML"     CACHE STRING "" FORCE)

#cleanup this temp var
set(CHOREGRAPHE-PLUGINS_tempdebug "CHOREGRAPHE-PLUGINS_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(CHOREGRAPHE-PLUGINS_tempdebug choregraphe-plugins_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (CHOREGRAPHE-PLUGINS_tempdebug)
  #use debug and optimized version
  flib(CHOREGRAPHE-PLUGINS OPTIMIZED choregraphe-plugins   PATHS "${_ROOT_DIR}/../../")
  flib(CHOREGRAPHE-PLUGINS DEBUG     choregraphe-plugins_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(CHOREGRAPHE-PLUGINS choregraphe-plugins PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(CHOREGRAPHE-PLUGINS)
