##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(DESKTOP)
set(DESKTOP_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/desktop/;${_ROOT_DIR}/../../../include/desktop/ftp/;${_ROOT_DIR}/../../../include/desktop/sync/;${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(DESKTOP_DEFINITIONS  "TIXML_USE_STL;TIXML_USE_STL;TIXML_USE_STL;TIXML_USE_STL;HAVE_IPV6" CACHE STRING "" FORCE)
set(DESKTOP_DEPENDS      "ALCOMMON;LIBIPPC;BOOST_SERIALIZATION;BOOST_DATE_TIME;BOOST_THREAD;ALVALUE;LIBCORE;BOOST;PTHREAD;BOOST_SIGNALS;TOOLS;BOOST_FILESYSTEM;LIBFINDIPPC;DL;PROXIES;LIBSOAP;TINYXML;RTTOOLS;LIBTHREAD;BOOST_PROGRAM_OPTIONS;LIBFACTORY;PYTHON-STATIC;ALBONJOURDISCOVERY;QT_QTCORE;QT_QTGUI;QT_QTNETWORK;QT_QTXML"     CACHE STRING "" FORCE)

#cleanup this temp var
set(DESKTOP_tempdebug "DESKTOP_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(DESKTOP_tempdebug desktop_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (DESKTOP_tempdebug)
  #use debug and optimized version
  flib(DESKTOP OPTIMIZED desktop   PATHS "${_ROOT_DIR}/../../")
  flib(DESKTOP DEBUG     desktop_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(DESKTOP desktop PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(DESKTOP)
