##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(LIBDAB)
set(LIBDAB_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(LIBDAB_DEFINITIONS  "_FILE_OFFSET_BITS=64" CACHE STRING "" FORCE)
set(LIBDAB_DEPENDS      "ARCHIVE;BOOST_REGEX;BOOST_FILESYSTEM;BOOST_DATE_TIME"     CACHE STRING "" FORCE)

#cleanup this temp var
set(LIBDAB_tempdebug "LIBDAB_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(LIBDAB_tempdebug dab_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (LIBDAB_tempdebug)
  #use debug and optimized version
  flib(LIBDAB OPTIMIZED dab   PATHS "${_ROOT_DIR}/../../")
  flib(LIBDAB DEBUG     dab_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(LIBDAB dab PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(LIBDAB)
