##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(LIBFINDIPPC)
set(LIBFINDIPPC_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(LIBFINDIPPC_DEFINITIONS  "" CACHE STRING "" FORCE)
set(LIBFINDIPPC_DEPENDS      "BOOST;BOOST_THREAD"     CACHE STRING "" FORCE)

#cleanup this temp var
set(LIBFINDIPPC_tempdebug "LIBFINDIPPC_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(LIBFINDIPPC_tempdebug findippc_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (LIBFINDIPPC_tempdebug)
  #use debug and optimized version
  flib(LIBFINDIPPC OPTIMIZED findippc   PATHS "${_ROOT_DIR}/../../")
  flib(LIBFINDIPPC DEBUG     findippc_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(LIBFINDIPPC findippc PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(LIBFINDIPPC)
