##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(LIBIPPC)
set(LIBIPPC_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(LIBIPPC_DEFINITIONS  "" CACHE STRING "" FORCE)
set(LIBIPPC_DEPENDS      "BOOST_SERIALIZATION;BOOST_DATE_TIME;BOOST_THREAD;ALVALUE;LIBCORE;BOOST;PTHREAD;BOOST_SIGNALS;TOOLS;BOOST_FILESYSTEM"     CACHE STRING "" FORCE)

#cleanup this temp var
set(LIBIPPC_tempdebug "LIBIPPC_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(LIBIPPC_tempdebug ippc_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (LIBIPPC_tempdebug)
  #use debug and optimized version
  flib(LIBIPPC OPTIMIZED ippc   PATHS "${_ROOT_DIR}/../../")
  flib(LIBIPPC DEBUG     ippc_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(LIBIPPC ippc PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(LIBIPPC)
