##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(LIBSOAP-STATIC)
set(LIBSOAP-STATIC_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(LIBSOAP-STATIC_DEFINITIONS  "TIXML_USE_STL" CACHE STRING "" FORCE)
set(LIBSOAP-STATIC_DEPENDS      "ALVALUE;LIBCORE;BOOST;PTHREAD;BOOST_SIGNALS;TOOLS;BOOST_FILESYSTEM;TINYXML"     CACHE STRING "" FORCE)

#cleanup this temp var
set(LIBSOAP-STATIC_tempdebug "LIBSOAP-STATIC_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(LIBSOAP-STATIC_tempdebug libsoap_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (LIBSOAP-STATIC_tempdebug)
  #use debug and optimized version
  flib(LIBSOAP-STATIC OPTIMIZED libsoap   PATHS "${_ROOT_DIR}/../../")
  flib(LIBSOAP-STATIC DEBUG     libsoap_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(LIBSOAP-STATIC libsoap PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(LIBSOAP-STATIC)
