##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(LIBVISION)
set(LIBVISION_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/alvision/;${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(LIBVISION_DEFINITIONS  "" CACHE STRING "" FORCE)
set(LIBVISION_DEPENDS      "LIBCORE;BOOST;PTHREAD;BOOST_SIGNALS;TOOLS;BOOST_FILESYSTEM;ALVALUE"     CACHE STRING "" FORCE)

#cleanup this temp var
set(LIBVISION_tempdebug "LIBVISION_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(LIBVISION_tempdebug libvision_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (LIBVISION_tempdebug)
  #use debug and optimized version
  flib(LIBVISION OPTIMIZED libvision   PATHS "${_ROOT_DIR}/../../")
  flib(LIBVISION DEBUG     libvision_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(LIBVISION libvision PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(LIBVISION)
