##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(NAOQICLIENT)
set(NAOQICLIENT_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(NAOQICLIENT_DEFINITIONS  "TIXML_USE_STL;TIXML_USE_STL;TIXML_USE_STL;TIXML_USE_STL;TIXML_USE_STL;TIXML_USE_STL;TIXML_USE_STL;TIXML_USE_STL" CACHE STRING "" FORCE)
set(NAOQICLIENT_DEPENDS      "LIBLAUNCHER;LIBCORE;BOOST;PTHREAD;BOOST_SIGNALS;TOOLS;BOOST_FILESYSTEM;ALVALUE;ALCOMMON;LIBIPPC;BOOST_SERIALIZATION;BOOST_DATE_TIME;BOOST_THREAD;LIBFINDIPPC;DL;PROXIES;LIBSOAP;TINYXML;RTTOOLS;LIBTHREAD;BOOST_PROGRAM_OPTIONS;LIBFACTORY;PYTHON-STATIC;LIBVISION"     CACHE STRING "" FORCE)

#cleanup this temp var
set(NAOQICLIENT_tempdebug "NAOQICLIENT_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(NAOQICLIENT_tempdebug naoqiclient_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (NAOQICLIENT_tempdebug)
  #use debug and optimized version
  flib(NAOQICLIENT OPTIMIZED naoqiclient   PATHS "${_ROOT_DIR}/../../")
  flib(NAOQICLIENT DEBUG     naoqiclient_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(NAOQICLIENT naoqiclient PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(NAOQICLIENT)
