##
## findmodule.cmake
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(NAOQI)
fprogram(NAOQI_binary naoqi-bin)
set(NAOQI_EXECUTABLE ${NAOQI_binary} CACHE STRING "" FORCE)
export_bin(NAOQI)
