##
## findmodule.cmake
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(PROXIES)
set(PROXIES_DEPENDS      ""     CACHE STRING "" FORCE)
set(PROXIES_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/alproxies/;${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(PROXIES_DEFINITIONS  "" CACHE STRING "" FORCE)
export_header(PROXIES)
