##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(RTTOOLS)
set(RTTOOLS_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/rttools/;${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(RTTOOLS_DEFINITIONS  "" CACHE STRING "" FORCE)
set(RTTOOLS_DEPENDS      "PTHREAD;LIBCORE;BOOST;BOOST_SIGNALS;TOOLS;BOOST_FILESYSTEM"     CACHE STRING "" FORCE)

#cleanup this temp var
set(RTTOOLS_tempdebug "RTTOOLS_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(RTTOOLS_tempdebug rttools_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (RTTOOLS_tempdebug)
  #use debug and optimized version
  flib(RTTOOLS OPTIMIZED rttools   PATHS "${_ROOT_DIR}/../../")
  flib(RTTOOLS DEBUG     rttools_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(RTTOOLS rttools PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(RTTOOLS)
