##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(TINYXML)
set(TINYXML_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/tinyxml/;${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(TINYXML_DEFINITIONS  "TIXML_USE_STL" CACHE STRING "" FORCE)
set(TINYXML_DEPENDS      ""     CACHE STRING "" FORCE)

#cleanup this temp var
set(TINYXML_tempdebug "TINYXML_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(TINYXML_tempdebug tinyxml_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (TINYXML_tempdebug)
  #use debug and optimized version
  flib(TINYXML OPTIMIZED tinyxml   PATHS "${_ROOT_DIR}/../../")
  flib(TINYXML DEBUG     tinyxml_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(TINYXML tinyxml PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(TINYXML)
