##
## findmodule.cmake
#
## Copyright (C) 2009 Aldebaran Robotics
##
## Autogenerated by T001CHAIN.
## Do not edit


#get the current directory
get_filename_component(_ROOT_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)

clean(TOOLS)
set(TOOLS_INCLUDE_DIR  "${_ROOT_DIR}/../../../include/altools/;${_ROOT_DIR}/../../../include/" CACHE STRING "" FORCE)
set(TOOLS_DEFINITIONS  "" CACHE STRING "" FORCE)
set(TOOLS_DEPENDS      "LIBCORE;BOOST;PTHREAD;BOOST_SIGNALS;BOOST_FILESYSTEM"     CACHE STRING "" FORCE)

#cleanup this temp var
set(TOOLS_tempdebug "TOOLS_tempdebug-NOTFOUND" CACHE INTERNAL "Cleared." FORCE)

#try to get the debug lib
find_library(TOOLS_tempdebug tools_d PATHS "${_ROOT_DIR}/../../" NO_DEFAULT_PATH)


if (TOOLS_tempdebug)
  #use debug and optimized version
  flib(TOOLS OPTIMIZED tools   PATHS "${_ROOT_DIR}/../../")
  flib(TOOLS DEBUG     tools_d PATHS "${_ROOT_DIR}/../../")
else()
  #use the default lib
  flib(TOOLS tools PATHS "${_ROOT_DIR}/../../")
endif()

export_lib(TOOLS)
